### ISSUE TITLE
Preparation for Flutter package transfer

### ISSUE THREAD

**Issue by slightfoot** [kf6gpe/dart-flutter-favorite#15]
The Flutter Community will be taking ownership of a few of the more minor plugins as they go to version 1.0. We would like to build a dashboard that will show us our packages scores based on this tooling. Please can we add @mhadaily and @jeroen-meijer to this repo.

/cc @csells

**Comment by kf6gpe** [comment]
Done for @mhadaily! Jay was already a contributor.

Thanks!
